[project]
name = "dvptestproject"
version = "0.1.0"
description = "Test Project for Django Vite Plugin"
requires-python = ">=3.11"
dependencies = [
    "django ~=4.2.20",
    "django_vite_plugin ~=4.0.5",
    "nodeenv ~=1.9.1",
]
